### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'conceptnet_edges2nd.txt'

### ISSUE THREAD

**Issue by 18rxliu** [WindyLee0822/TREA#2]
The conceptnet_edges2nd.txt seems to be missing, it would be grateful if u can upload this file!

**Comment by WindyLee0822** [comment]
Thanks for proposing the issue. I've uploaded it.

**Comment by 18rxliu** [comment]
Still i can't run the code by "python run_publish.py -is_finetune mov";

something wrong occur in:
Traceback (most recent call last):
  File "run_publish.py", line 1087, in <module>
    loop.train()
  File "run_publish.py", line 240, in train
    entity_rec.to(self.device),branch.to(self.device),m_branch.to(self.device),cur_l.to(self.device), leaf.to(self.device),test=False)
  File "C:\Users\Racy\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\LocalCache\local-packages\Python37\site-packages\pyenv-win\versions\3.6.8\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\Files\Deeplearing\TREA\TREA\model.py", line 906, in forward
    db_nodes_features = self.dbpedia_RGCN(None, self.db_edge_idx, self.db_edge_type)

And the wrong type is:    assert edge_index.dtype == torch.long AssertionError
Actually i am a noob in programing, so it's really hard for me to figure out what to do. It takes me a lot time to try but i don't wanna give up because i really appreciate your work!

**Comment by WindyLee0822** [comment]
If you are running our original codes, i think mistakes may raise from the package version. 
Our version of the relevant package is torch-geometric ==2.3.1

You can first try modify "db_nodes_features = self.dbpedia_RGCN(None, self.db_edge_idx, self.db_edge_type)"  to "db_nodes_features = self.dbpedia_RGCN(None, self.db_edge_idx.long(), self.db_edge_type)". I do not know whether modifying this row works. If not, you can try to revise the version of torch-geometric to 2.3.1.

**Comment by 18rxliu** [comment]
Thanks! It is running after i changed all related parameters'type into torch.Longtensor, and i found that i can't upgrade torch-geometric to 2.3.1 because it require Python 3.8 above while my is 3.6. Can i know the version of the main packages for your project?

**Comment by WindyLee0822** [comment]
Happy to hear that you have solved the problem. We use Python 3.8 and the package versions of Pytorch are
torch                    1.13.1
torch-cluster            1.6.0+pt113cu117
torch-geometric          2.3.1
torch-scatter            2.1.0+pt113cu117
torch-sparse             0.6.16+pt113cu117
